### ISSUE TITLE
Customize openapi.json at root level

### ISSUE THREAD

**Issue by clayrisser** [strongloop/loopback-next#2062]
How can I customize the openapi.json file at the root level. I want to add the following config . . .

```yaml
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
```
