### ISSUE TITLE
Exist readOnly in model?

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-next#2782]
Is the property **readOnly** in loopback 4? I've been looking for a while but I have not found anything about it

```
type: object
properties:
  id:
    # Returned by GET, not used in POST/PUT/PATCH
    type: integer
    readOnly: true
  username:
    type: string
  password:
    # Used in POST/PUT/PATCH, not returned by GET
    type: string
    writeOnly: true
```
